/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PullRequestsRouteImport } from './routes/pull-requests'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as GithubRouteImport } from './routes/github'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DevopsRouteImport } from './routes/devops'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeReviewIndexRouteImport } from './routes/code-review.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as CodeReviewProjectIdRouteImport } from './routes/code-review.$projectId'
import { Route as ApiEditorChatRouteImport } from './routes/api/editor-chat'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestsRoute = PullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DevopsRoute = DevopsRouteImport.update({
  id: '/devops',
  path: '/devops',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeReviewIndexRoute = CodeReviewIndexRouteImport.update({
  id: '/code-review/',
  path: '/code-review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const CodeReviewProjectIdRoute = CodeReviewProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => CodeReviewRoute,
} as any)
const ApiEditorChatRoute = ApiEditorChatRouteImport.update({
  id: '/api/editor-chat',
  path: '/api/editor-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/devops': typeof DevopsRoute
  '/editor': typeof EditorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/github': typeof GithubRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/pull-requests': typeof PullRequestsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/telegram': typeof TelegramRoute
  '/templates': typeof TemplatesRoute
  '/update-password': typeof UpdatePasswordRoute
  '/workspace': typeof WorkspaceRoute
  '/api/editor-chat': typeof ApiEditorChatRoute
  '/code-review/$projectId': typeof CodeReviewProjectIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/code-review/': typeof CodeReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/devops': typeof DevopsRoute
  '/editor': typeof EditorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/github': typeof GithubRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/pull-requests': typeof PullRequestsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/telegram': typeof TelegramRoute
  '/templates': typeof TemplatesRoute
  '/update-password': typeof UpdatePasswordRoute
  '/workspace': typeof WorkspaceRoute
  '/api/editor-chat': typeof ApiEditorChatRoute
  '/code-review/$projectId': typeof CodeReviewProjectIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/code-review': typeof CodeReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/devops': typeof DevopsRoute
  '/editor': typeof EditorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/github': typeof GithubRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/pull-requests': typeof PullRequestsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/telegram': typeof TelegramRoute
  '/templates': typeof TemplatesRoute
  '/update-password': typeof UpdatePasswordRoute
  '/workspace': typeof WorkspaceRoute
  '/api/editor-chat': typeof ApiEditorChatRoute
  '/code-review/$projectId': typeof CodeReviewProjectIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/code-review/': typeof CodeReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/api-keys'
    | '/audit-log'
    | '/auth'
    | '/billing'
    | '/devops'
    | '/editor'
    | '/forgot-password'
    | '/github'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/projects'
    | '/pull-requests'
    | '/reports'
    | '/settings'
    | '/team'
    | '/telegram'
    | '/templates'
    | '/update-password'
    | '/workspace'
    | '/api/editor-chat'
    | '/code-review/$projectId'
    | '/projects/$id'
    | '/code-review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/api-keys'
    | '/audit-log'
    | '/auth'
    | '/billing'
    | '/devops'
    | '/editor'
    | '/forgot-password'
    | '/github'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/projects'
    | '/pull-requests'
    | '/reports'
    | '/settings'
    | '/team'
    | '/telegram'
    | '/templates'
    | '/update-password'
    | '/workspace'
    | '/api/editor-chat'
    | '/code-review/$projectId'
    | '/projects/$id'
    | '/code-review'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/api-keys'
    | '/audit-log'
    | '/auth'
    | '/billing'
    | '/devops'
    | '/editor'
    | '/forgot-password'
    | '/github'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/projects'
    | '/pull-requests'
    | '/reports'
    | '/settings'
    | '/team'
    | '/telegram'
    | '/templates'
    | '/update-password'
    | '/workspace'
    | '/api/editor-chat'
    | '/code-review/$projectId'
    | '/projects/$id'
    | '/code-review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AuditLogRoute: typeof AuditLogRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  DevopsRoute: typeof DevopsRoute
  EditorRoute: typeof EditorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GithubRoute: typeof GithubRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PullRequestsRoute: typeof PullRequestsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  TelegramRoute: typeof TelegramRoute
  TemplatesRoute: typeof TemplatesRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiEditorChatRoute: typeof ApiEditorChatRoute
  CodeReviewIndexRoute: typeof CodeReviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests': {
      id: '/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof PullRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devops': {
      id: '/devops'
      path: '/devops'
      fullPath: '/devops'
      preLoaderRoute: typeof DevopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-review/': {
      id: '/code-review/'
      path: '/code-review'
      fullPath: '/code-review/'
      preLoaderRoute: typeof CodeReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/code-review/$projectId': {
      id: '/code-review/$projectId'
      path: '/$projectId'
      fullPath: '/code-review/$projectId'
      preLoaderRoute: typeof CodeReviewProjectIdRouteImport
      parentRoute: typeof CodeReviewRoute
    }
    '/api/editor-chat': {
      id: '/api/editor-chat'
      path: '/api/editor-chat'
      fullPath: '/api/editor-chat'
      preLoaderRoute: typeof ApiEditorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ApiKeysRoute: ApiKeysRoute,
  AuditLogRoute: AuditLogRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  DevopsRoute: DevopsRoute,
  EditorRoute: EditorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GithubRoute: GithubRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  PullRequestsRoute: PullRequestsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  TelegramRoute: TelegramRoute,
  TemplatesRoute: TemplatesRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiEditorChatRoute: ApiEditorChatRoute,
  CodeReviewIndexRoute: CodeReviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
